# 자바 예외

웹 애플리케이션의 경우 여러 사용자의 요청을 처리하기 때문에 하나의 예외 때문에 시스템이 종료되면 안된다. WAS가 해당 예외를 받아서 처리하는데, 주로 사용자에게 개발자가 지정한, 오류 페이지를
보여준다.


![image](https://user-images.githubusercontent.com/65898555/181137177-ac838906-e3cd-4b17-9603-a6a04392b132.png)

**Object** : 예외도 객체이다. 모든 객체의 최상위 부모는 Object 이므로 예외의 최상위 부모도 Object이다.

**Throwable** : 최상위 예외이다. 하위에 Exception 과 Error 가 있다.

**Error** : 메모리 부족이나 심각한 시스템 오류와 같이 애플리케이션에서 복구 불가능한 시스템 예외이다. 

애플리케이션 개발자는 이 예외를 잡으려고 해서는 안된다. 상위 예외를 catch 로 잡으면 그 하위 예외까지 함께 잡는다. 따라서 애플리케이션 로직에서는 Throwable 예외도 잡으면 안되는데, 앞서 이야기한 Error 예외도 함께 잡을 수 있기 때문에다. 
애플리케이션 로직은 이런 이유로 Exception 부터 필요한 예외로 생각하고 잡으면 된다. 참고로 Error도 언체크 예외이다.

**Exception** : 체크 예외. 애플리케이션 로직에서 사용할 수 있는 실질적인 최상위 예외이다. Exception 과 그 하위 예외는 모두 컴파일러가 체크하는 체크 예외이다. 단 RuntimeException은 예외로 한다.

**RuntimeException** : 언체크 예외, 런타임 예외. 컴파일러가 체크 하지 않는 언체크 예외이다. RuntimeException과 그 자식 예외는 모두 언체크 예외이다.

Exception 을 상속받으면 체크 예외가 된다. RuntimeException을 상속받으면 언체크 예외가 된다. 이런 규칙은 자바 언어에서 문법으로 정한 것이다.

![image](https://user-images.githubusercontent.com/65898555/181137444-fffffa31-2b6d-46be-a126-7012f5d66a7a.png)

![image](https://user-images.githubusercontent.com/65898555/181137454-95896a94-28de-4b01-afd5-fd759d3a961d.png)

예외는 폭탄 돌리기와 같다. 잡아서 처리하거나, 처리할 수 없으면 밖으로 던져야한다. 예외를 처리하지 못하면 호출한 곳으로 예외를 계속 던지게 된다.


1. 예외는 잡아서 처리하거나 던져야 한다.
2. 예외를 잡거나 던질 때 지정한 예외뿐만 아니라 그 예외의 자식들도 함께 처리된다. 예를 들어서 Exception을 catch로 잡으면 그 하위 예외들도 모두 잡을 수 있다. 예를 들어서 Exception을 throws로 던지면 그 하위 예외들도 모두 던질 수 있다.


자바에서 예외처리는 catch로 하는데, catch는 해당 타입과 그 하위 타입을 모두 잡을 수 있다.

---

체크 예외: 예외를 잡아서 처리하지 않으면 항상 throws 에 던지는 예외를 선언해야 한다.
언체크 예외: 예외를 잡아서 처리하지 않아도 throws 를 생략할 수 있다. 필요한 경우 catch문을 통해 예외를 잡을 수 있다.

---


# 체크 예외의 문제점

**기본적으로 언체크(런타임) 예외를 사용한다.**

체크 예외는 비즈니스 로직상 의도적으로 던지는 예외에만 사용한다.

이 경우 해당 예외를 잡아서 반드시 처리해야 하는 문제일 때만 체크 예외를 사용해야 한다. 예를 계좌 이체 실패 예외, 결제시 포인트 부족 예외 등 심각한 문제는 개발자가 실수로 예외를 놓치면
안된다고 생각하면 체크예외로 만들어 컴파일러를 통해 놓친 예외를 인지할 수 있다.

체크 예외는 컴파일러가 예외 누락을 체크해주기 때문에 개발자가 실수로 예외를 놓치는 것을 막아준다.  그래서 항상 명시적으로 예외를 잡아서 처리하거나, 처리할 수 없을 때는 예외를 던지도록 method() throws 예외로 선언해야 한다.

![image](https://user-images.githubusercontent.com/65898555/181138554-46f1c97e-ef96-48ad-9014-875377ab829f.png)

1. 리포지토리는 DB에 접근해서 데이터를 저장하고 관리한다. 여기서는 SQLException 체크 예외를 던진다. NetworkClient는 외부 네트워크에 접속해서 어떤 기능을 처리하는 객체이다. 여기서는 ConnectException 체크 예외를 던진다.
2. 서비스는 리포지토리와 NetworkClient 를 둘다 호출한다. 따라서 두 곳에서 올라오는 체크 예외인 SQLException과 ConnectException 을 처리해야 한다.
그런데 서비스는 이 둘을 처리할 방법을 모른다. ConnectException 처럼 연결이 실패하거나, SQLException 처럼 데이터베이스에서 발생하는 문제처럼 심각한 문제들은 대부분 애플리케이션 로직에서 처리할 방법이 없다.
서비스는 SQLException 과 ConnectException 를 처리할 수 없으므로 둘다 밖으로 던진다. 체크 예외이기 때문에 던질 경우 다음과 같이 선언해야 한다. ```method() throws SQLException, ConnectException```
3. 컨트롤러도 두 예외를 처리할 방법이 없다. 다음을 선언해서 예외를 밖으로 던진다. ```method() throws SQLException, ConnectException```
4. 웹 애플리케이션이라면 서블릿의 오류 페이지나, 또는 스프링 MVC가 제공하는 ControllerAdvice에서 이런 예외를 공통으로 처리한다. API라면 보통 HTTP 상태코드 500(내부 서버 오류)을 사용해서 응답을 내려준다.

```java
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import java.net.ConnectException;
import java.sql.SQLException;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@Slf4j
public class CheckedAppTest {
  @Test
  void checked() {
    Controller controller = new Controller();
    assertThatThrownBy(() -> controller.request())
    .isInstanceOf(Exception.class);
  }
  
  static class Controller {
    Service service = new Service();
    public void request() throws SQLException, ConnectException {
      service.logic();
    }
  }
  
  static class Service {
    Repository repository = new Repository();
    NetworkClient networkClient = new NetworkClient();
    public void logic() throws SQLException, ConnectException {
      repository.call();
      networkClient.call();
    }
  }
  
  static class NetworkClient {
    public void call() throws ConnectException {
      throw new ConnectException("연결 실패");
    }
  }
  
  static class Repository {
    public void call() throws SQLException {
      throw new SQLException("ex");
    }
  }
}
```
위 코드에서는 두가지 문제가 있다.

1. 복구 불가능한 예외
2. 의존 관계에 대한 문제

1. 복구 불가능한 예외<br>
대부분의 예외는 복구가 불가능하다. 일부 복구가 가능한 예외도 있지만 아주 적다.
SQLException을 예를 들면 데이터베이스에 무언가 문제가 있어서 발생하는 예외이다. SQL 문법에
문제가 있을 수도 있고, 데이터베이스 자체에 뭔가 문제가 발생했을 수도 있다. 데이터베이스 서버가 중간에
다운 되었을 수도 있다. 이런 문제들은 대부분 복구가 불가능하다. 특히나 대부분의 서비스나 컨트롤러는
이런 문제를 해결할 수는 없다. 따라서 이런 문제들은 일관성 있게 공통으로 처리해야 한다. 오류 로그를 남기고 개발자가 해당 오류를 빠르게 인지하는 것이 필요하다. 서블릿 필터, 스프링 인터셉터, 스프링의
ControllerAdvice 를 사용하면 이런 부분을 깔끔하게 공통으로 해결할 수 있다.

2. 의존 관계에 대한 문제<br>
체크 예외의 또 다른 심각한 문제는 예외에 대한 의존 관계 문제이다.
앞서 대부분의 예외는 복구 불가능한 예외라고 했다. 그런데 체크 예외이기 때문에 컨트롤러나 서비스
입장에서는 본인이 처리할 수 없어도 어쩔 수 없이 throws 를 통해 던지는 예외를 선언해야 한다.

```java
class Controller {
  public void request() throws SQLException, ConnectException {
    service.logic();
  }
}
class Service {
  public void logic() throws SQLException, ConnectException {
    repository.call();
    networkClient.call();
  }
}
```
```throws SQLException, ConnectException```은 서비스, 컨트롤러에서 java.sql.SQLException을 의존하는 문제가 발생한다.

향후 리포지토리를 JDBC 기술이 아닌 다른 기술로 변경한다면, 그래서 SQLException이 아니라 예를 들어서 JPAException으로 예외가 변경된다면 어떻게 될까?(참고로 JPA 예외는 실제 이렇지는 않다.)

SQLException에 의존하던 모든 서비스, 컨트롤러의 코드를 JPAException에 의존하도록 고쳐야 한다. 서비스나 컨트롤러 입장에서는 어차피 본인이 처리할 수 도 없는 예외를 의존해야 하는 큰 단점이 발생하게
된다. 결과적으로 OCP, DI를 통해 클라이언트 코드의 변경 없이 대상 구현체를 변경할 수 있다는 장점이 체크 예외 때문에 발목을 잡게 된다.


![image](https://user-images.githubusercontent.com/65898555/181139350-f400e794-c6ef-4c02-b9bc-0bd1d3745668.png)

처리할 수 있는 체크 예외라면 서비스나 컨트롤러에서 처리하겠지만, 지금처럼 데이터베이스나 네트워크 통신처럼 시스템 레벨에서 올라온 예외들은 대부분 복구가 불가능하다. 그리고 실무에서 발생하는 대부분의
예외들은 이런 시스템 예외들이다. 문제는 이런 경우에 체크 예외를 사용하면 아래에서 올라온 복구 불가능한 예외를 서비스, 컨트롤러 같은 각각의 클래스가 모두 알고 있어야 한다. 그래서 불필요한 의존관계 문제가 발생하게 된다.

```java
void method() throws SQLException, ConnectException {..}

void method() throws Exception {..}
```
최상위 예외인 Exception 을 던져도 문제를 해결할 수 있다. 이렇게 하면 Exception 은 물론이고 그 하위 타입인 SQLException , ConnectException 도 함께 던지게 된다. 코드가 깔끔해지는 것 같지만, Exception 은 최상위 타입이므로 모든 체크 예외를 다 밖으로
던지는 문제가 발생한다.

결과적으로 체크 예외의 최상위 타입인 Exception을 던지게 되면 다른 체크 예외를 체크할 수 있는 기능이 무효화 되고, 중요한 체크 예외를 다 놓치게 된다. 중간에 중요한 체크 예외가 발생해도 컴파일러는 Exception을 던지기 때문에 문법에 맞다고 판단해서 컴파일 오류가 발생하지 않는다.
이렇게 하면 모든 예외를 다 던지기 때문에 체크 예외를 의도한 대로 사용하는 것이 아니다. 따라서 꼭 필요한 경우가 아니면 이렇게 Exception 자체를 밖으로 던지는 것은 좋지 않은 방법이다.



# 런타임 예외(언체크예외) 활용


![image](https://user-images.githubusercontent.com/65898555/181139677-444067c1-928a-486e-95a3-9d4b0645455e.png)

SQLException을 런타임 예외인 RuntimeSQLException 으로 변환했다.

런타임 예외이기 때문에 서비스, 컨트롤러는 해당 예외들을 처리할 수 없다면 별도의 선언 없이 그냥 두면 된다.

```java
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import java.sql.SQLException;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@Slf4j
public class UncheckedAppTest {
  @Test
  void unchecked() {
    Controller controller = new Controller();
    assertThatThrownBy(() -> controller.request())
    .isInstanceOf(Exception.class);
  }
  
  @Test
  void printEx() {
    Controller controller = new Controller();
    try {
    controller.request();
    } catch (Exception e) {
      //e.printStackTrace();
      log.info("ex", e);
    }
  }
  
  static class Controller {
    Service service = new Service();
    public void request() {
      service.logic();
    }
  }
  
  static class Service {
    Repository repository = new Repository();
    NetworkClient networkClient = new NetworkClient();
    public void logic() {
      repository.call();
      networkClient.call();
    }
  }
  
  static class NetworkClient {
    public void call() {
      throw new RuntimeConnectException("연결 실패");
    }
  }
  
  static class Repository {
    public void call() {
      try {
        runSQL();
      } catch (SQLException e) {
        throw new RuntimeSQLException(e);
      }
    }
    private void runSQL() throws SQLException {
      throw new SQLException("ex");
    }
  }
  
  static class RuntimeConnectException extends RuntimeException {
    public RuntimeConnectException(String message) {
      super(message);
    }
  }
  
  static class RuntimeSQLException extends RuntimeException {
    public RuntimeSQLException() {
    }
    public RuntimeSQLException(Throwable cause) {
      super(cause);
    }
  }
}
```

리포지토리에서 체크 예외인 SQLException이 발생하면 런타임 예외인 RuntimeSQLException으로 전환해서 예외를 던진다.

NetworkClient는 단순히 기존 체크 예외를 RuntimeConnectException이라는 런타임 예외가 발생하도록 코드를 바꾸었다.


런타임 예외는 대부분 복구 불가능한 예외이다. 시스템에서 발생한 예외는 대부분 복구 불가능 예외이다. 런타임 예외를 사용하면 서비스나 컨트롤러가 이런 복구 불가능한 예외를 신경쓰지 않아도 된다. 물론 이렇게 복구 불가능한 예외는 일관성 있게 공통으로
처리해야 한다.

런타임 예외는 해당 객체가 처리할 수 없는 예외는 무시하면 된다. 따라서 ```method() throws RuntimeSQLException, RuntimeConnectException```생략이 가능하고, 체크 예외 처럼 예외를 강제로 의존하지 않아도 된다.

![image](https://user-images.githubusercontent.com/65898555/181140391-73333c2b-7461-4fbb-95b3-e2487b10e3a7.png)

런타임 예외를 사용하면 중간에 기술이 변경되어도 해당 예외를 사용하지 않는 컨트롤러, 서비스에서는 코드를 변경하지 않아도 된다.

구현 기술이 변경되는 경우, 예외를 공통으로 처리하는 곳에서는 예외에 따른 다른 처리가 필요할 수 있다. 하지만 공통 처리하는 한곳만 변경하면 되기 때문에 변경의 영향 범위는 최소화 된다.

---

최근 라이브러리들은 대부분 런타임 예외를 기본으로 제공한다. JPA 기술도 런타임 예외를 사용한다. 스프링도 대부분 런타임 예외를 제공한다.
런타임 예외도 필요하면 잡을 수 있기 때문에 필요한 경우에는 잡아서 처리하고, 그렇지 않으면 자연스럽게 던지도록 둔다. 그리고 예외를 공통으로 처리하는 부분을 앞에 만들어서 처리하면 된다.
추가로 런타임 예외는 놓칠 수 있기 때문에 문서화가 중요하다. 또는 코드에 throws 런타임예외 을 남겨서 중요한 예외를 인지할 수 있게 해준다.


# 예외 포함과 스택 트레이스

예외를 전환할 때는 기존 예외를 포함해야 한다. 그렇지 않으면 스택 트레이스를 확인할 때 심각한 문제가 발생한다.

```java
public void call() {
  try {
    runSQL();
  } catch (SQLException e) {
    throw new RuntimeSQLException(e); //기존 예외(e) 포함
  }
}
```
기존 예외를 포함하는 경우

```java
public void call() {
  try {
    runSQL();
  } catch (SQLException e) {
    throw new RuntimeSQLException(); //기존 예외(e) 제외
  }  
}
```
기존 예외를 포함하지 않는 경우

예외를 포함하지 않아서 기존에 발생한 java.sql.SQLException과 스택 트레이스를 확인할 수 없다. 변환한 RuntimeSQLException부터 예외를 확인할 수 있다. 만약 실제 DB에 연동했다면 DB에서 발생한
예외를 확인할 수 없는 심각한 문제가 발생한다. 예외를 전환할 때는 기존 예외를 포함해야 한다.


# 데이터 접근 예외 직접 만들기


![image](https://user-images.githubusercontent.com/65898555/181141744-8590731a-c52e-49ee-86c7-b9abd79fdd19.png)

데이터베이스 오류에 따라서 특정 예외는 복구하고 싶을 수 있다.

예를 들어서 회원 가입시 DB에 이미 같은 ID가 있으면 ID 뒤에 숫자를 붙여서 새로운 ID를 만들어야 한다고 가정해보자. ID를 hello 라고 가입 시도 했는데, 이미 같은 아이디가 있으면 hello12345 와 같이 뒤에 임의의 숫자를
붙여서 가입하는 것이다.

데이터를 DB에 저장할 때 같은 ID가 이미 데이터베이스에 저장되어 있다면, 데이터베이스는 오류 코드를 반환하고, 이 오류 코드를 받은 JDBC 드라이버는 SQLException을 던진다. 그리고 SQLException 에는 데이터베이스가 제공하는 errorCode 라는 것이 들어있다
SQLException 내부에 들어있는 errorCode를 활용하면 데이터베이스에서 어떤 문제가 발생했는지 확인할 수 있다.

참고로 같은 오류여도 각각의 데이터베이스마다 정의된 오류 코드가 다르다. 따라서 오류 코드를 사용할 때는 데이터베이스 메뉴얼을 확인해야 한다.

서비스 계층에서는 예외 복구를 위해 키 중복 오류를 확인할 수 있어야 한다. 그래야 새로운 ID를 만들어서 다시 저장을 시도할 수 있기 때문이다. 이러한 과정이 바로 예외를 확인해서 복구하는 과정이다. 
리포지토리는 SQLException을 서비스 계층에 던지고 서비스 계층은 이 예외의 오류 코드를 확인해서 키 중복 오류( 23505 )인 경우 새로운 ID를 만들어서 다시 저장하면 된다.
그런데 SQLException에 들어있는 오류 코드를 활용하기 위해 SQLException을 서비스 계층으로 던지게 되면, 서비스 계층이 SQLException 이라는 JDBC 기술에 의존하게 되어,  이 문제를 해결하려면 앞서 배운 것 처럼 리포지토리에서 예외를 변환해서 던지면 된다. ```SQLException->MyDuplicateKeyException```


```java
public class MyDuplicateKeyException extends MyDbException {
  public MyDuplicateKeyException() {
  }
  
  public MyDuplicateKeyException(String message) {
    super(message);
  }
  
  public MyDuplicateKeyException(String message, Throwable cause) {
    super(message, cause);
  }
  
  public MyDuplicateKeyException(Throwable cause) {
    super(cause);
  }
}
```
MyDuplicateKeyException이라는 이름을 지었다. 이 예외는 데이터 중복의 경우에만 던져야 한다.
이 예외는 우리가 직접 만든 것이기 때문에, JDBC나 JPA 같은 특정 기술에 종속적이지 않다. 따라서 이 예외를 사용하더라도 서비스 계층의 순수성을 유지할 수 있다. (향후 JDBC에서 다른 기술로 바꾸어도 이
예외는 그대로 유지할 수 있다.)

```java
import hello.jdbc.domain.Member;
import hello.jdbc.repository.ex.MyDbException;
import hello.jdbc.repository.ex.MyDuplicateKeyException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Random;
import static hello.jdbc.connection.ConnectionConst.*;
import static org.springframework.jdbc.support.JdbcUtils.closeConnection;
import static org.springframework.jdbc.support.JdbcUtils.closeStatement;

public class ExTranslatorV1Test {
  Repository repository;
  Service service;
  @BeforeEach
  void init() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource(URL,USERNAME, PASSWORD);
    repository = new Repository(dataSource);
    service = new Service(repository);
  }
  
   @Test
  void duplicateKeySave() {
    service.create("myId");
    service.create("myId");//같은 ID 저장 시도
  }
  
  @Slf4j
  @RequiredArgsConstructor
  static class Service {
    private final Repository repository;
    public void create(String memberId) {
      try {
        repository.save(new Member(memberId, 0));
        log.info("saveId={}", memberId);
      } catch (MyDuplicateKeyException e) {
        log.info("키 중복, 복구 시도");
        String retryId = generateNewId(memberId);
        log.info("retryId={}", retryId);
        repository.save(new Member(retryId, 0));
      } catch (MyDbException e) {
        log.info("데이터 접근 계층 예외", e);
        throw e;
      }
    }
  
    private String generateNewId(String memberId) {
      return memberId + new Random().nextInt(10000);
    }
  }
  
  @RequiredArgsConstructor
  static class Repository {
    private final DataSource dataSource;
    public Member save(Member member) {
      String sql = "insert into member(member_id, money) values(?, ?)";
      Connection con = null;
      PreparedStatement pstmt = null;
      try {
        con = dataSource.getConnection();
        pstmt = con.prepareStatement(sql);
        pstmt.setString(1, member.getMemberId());
        pstmt.setInt(2, member.getMoney());
        pstmt.executeUpdate();
        return member;
      } catch (SQLException e) {
        //h2 db
        if (e.getErrorCode() == 23505) {
          throw new MyDuplicateKeyException(e);
        }
        throw new MyDbException(e);
      } finally {
        closeStatement(pstmt);
        closeConnection(con);
      }
    }
  }
}
```
```
Service - saveId=myId
Service - 키 중복, 복구 시도
Service - retryId=myId492
```

위 코드에는 문제점이 있다.
데이터베이스가 전달하는 오류는 키 중복 뿐만 아니라 락이 걸린 경우, SQL 문법에 오류 있는 경우 등등 수십 수백가지 오류 코드가 있다. SQL ErrorCode는 각각의 데이터베이스 마다 다르다. 결과적으로 데이터베이스가 변경될 때 마다 ErrorCode도 모두 변경해야 한다.


# 스프링 예외 추상화 이해

![image](https://user-images.githubusercontent.com/65898555/181142721-3c92cd9e-7b00-4421-88d9-86c7fe21f159.png)

그림을 단순화 하기 위해 일부 계층.

스프링은 데이터 접근 계층에 대한 수십 가지 예외를 정리해서 일관된 예외 계층을 제공한다.

각각의 예외는 특정 기술에 종속적이지 않게 설계되어 있다. 따라서 서비스 계층에서도 스프링이 제공하는 예외를 사용하면 된다. 예를 들어서 JDBC 기술을 사용하든, JPA 기술을 사용하든 스프링이 제공하는 예외를 사용하면 된다.
JDBC나 JPA를 사용할 때 발생하는 예외를 스프링이 제공하는 예외로 변환해주는 역할도 스프링이 제공한다.

예외의 최고 상위는 ```org.springframework.dao.DataAccessException``` 이다. 
그림에서 보는 것 처럼 런타임 예외를 상속 받았기 때문에 스프링이 제공하는 데이터 접근 계층의 모든 예외는 런타임 예외이다.

DataAccessException은 크게 2가지로 구분하는데 NonTransient예외와 Transient예외이다.

Transient는 일시적이라는 뜻이다. Transient 하위 예외는 동일한 SQL을 다시 시도했을 때 성공할 가능성이 있다.
예를 들어서 쿼리 타임아웃, 락과 관련된 오류들이다. 이런 오류들은 데이터베이스 상태가 좋아지거나, 락이 풀렸을 때 다시 시도하면 성공할 수 도 있다.

NonTransient는 일시적이지 않다는 뜻이다. 같은 SQL을 그대로 반복해서 실행하면 실패한다. SQL 문법 오류, 데이터베이스 제약조건 위배 등이 있다.


# 스프링이 제공하는 예외 변환기

스프링은 데이터베이스에서 발생하는 오류 코드를 스프링이 정의한 예외로 자동으로 변환해주는 변환기를 제공한다.

```java
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.BadSqlGrammarException;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator;
import org.springframework.jdbc.support.SQLExceptionTranslator;
import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import static hello.jdbc.connection.ConnectionConst.*;
import static org.assertj.core.api.Assertions.assertThat;

@Slf4j
public class SpringExceptionTranslatorTest {
  DataSource dataSource;
  
  @BeforeEach
  void init() {
    dataSource = new DriverManagerDataSource(URL, USERNAME, PASSWORD);
  }
  
  @Test
  void exceptionTranslator() {
    String sql = "select bad grammar";
    try {
      Connection con = dataSource.getConnection();
      PreparedStatement stmt = con.prepareStatement(sql);
      stmt.executeQuery();
    } catch (SQLException e) {
      assertThat(e.getErrorCode()).isEqualTo(42122);
      //org.springframework.jdbc.support.sql-error-codes.xml
      SQLExceptionTranslator exTranslator = new SQLErrorCodeSQLExceptionTranslator(dataSource);
      //org.springframework.jdbc.BadSqlGrammarException
      DataAccessException resultEx = exTranslator.translate("select", sql,e);
      log.info("resultEx", resultEx);

      assertThat(resultEx.getClass()).isEqualTo(BadSqlGrammarException.class);
    }
  }
}
```
```java
SQLExceptionTranslator exTranslator = new SQLErrorCodeSQLExceptionTranslator(dataSource);
DataAccessException resultEx = exTranslator.translate("select", sql, e);
```
스프링이 제공하는 SQL 예외 변환기는 다음과 같이 사용하면 된다.

translate() 메서드의 첫번째 파라미터는 읽을 수 있는 설명이고, 두번째는 실행한 sql, 마지막은 발생된 SQLException을 전달하면 된다. 이렇게 하면 적절한 스프링 데이터 접근 계층의 예외로 변환해서 반환해준다.

예제에서는 SQL 문법이 잘못되었으므로 BadSqlGrammarException을 반환한다.
반환 타입은 최상위 타입인 DataAccessException이지만 실제로는 BadSqlGrammarException 예외가 반환된다. 
참고로 BadSqlGrammarException 은 최상위 타입인 DataAccessException 를 상속 받아서 만들어진다.

```xml
<bean id="H2" class="org.springframework.jdbc.support.SQLErrorCodes">
<property name="badSqlGrammarCodes">
<value>42000,42001,42101,42102,42111,42112,42121,42122,42132</value>
</property>
<property name="duplicateKeyCodes">
<value>23001,23505</value>
</property>
</bean>
<bean id="MySQL" class="org.springframework.jdbc.support.SQLErrorCodes">
<property name="badSqlGrammarCodes">
<value>1054,1064,1146</value>
</property>
<property name="duplicateKeyCodes">
<value>1062</value>
</property>
</bean>
```
이것이 가능한 이유는 ```org.springframework.jdbc.support.sql-error-codes.xml```파일에 있다.

스프링 SQL 예외 변환기는 SQL ErrorCode를 이 파일에 대입해서 어떤 스프링 데이터 접근 예외로 전환해야 할지 찾아낸다. 
해당 파일을 확인해보면 10개 이상의 우리가 사용하는 대부분의 관계형 데이터베이스를 지원하는 것을 확인할 수 있다.

---

스프링은 데이터 접근 계층에 대한 일관된 예외 추상화를 제공한다.

스프링은 예외 변환기를 통해서 SQLException의 ErrorCode 에 맞는 적절한 스프링 데이터 접근 예외로 변환해준다.

만약 서비스, 컨트롤러 계층에서 예외 처리가 필요하면 특정 기술에 종속적인 SQLException 같은 예외를 직접 사용하는 것이 아니라, 스프링이 제공하는 데이터 접근 예외를 사용하면 된다.
스프링 예외 추상화와 덕분에 특정 기술에 종속적이지 않게 되었다. 이제 JDBC에서 JPA같은 기술로 변경되어도 예외로 인한 변경을 최소화 할 수 있다. 향후 JDBC에서 JPA로 구현 기술을 변경하더라도,  스프링은 JPA 예외를 적절한 스프링 데이터 접근 예외로 변환해준다.

물론 스프링이 제공하는 예외를 사용하기 때문에 스프링에 대한 기술 종속성은 발생한다. 스프링에 대한 기술 종속성까지 완전히 제거하려면 예외를 모두 직접 정의하고 예외 변환도 직접 하면 되지만, 실용적인 방법은 아니다.

